annexF:
  blob:
    application:
      dtd: "application-body-v1-7.dtd"
      name: "application-body.xml"
      path: "procedures/common/annexf/dtd/WIPO-1.16/application-body-v1-7.dtd"
      version: "1.7"
      xslt: "procedures/common/annexf/xslt/application-body-xml-v1-7.xslt"
      annexFDocumentName: "APPBODYXML"
    feePdf:
      name: "feesheetint.pdf"
      xslt: "NATPAT/annexf/xslt/fee-pdf.xslt"
      annexFDocumentName: "FEESHEETINT"
      template: "header"
    inventor:
      name: "f1002-1.pdf"
      xslt: "NATPAT/annexf/xslt/inventor-pdf.xslt"
      annexFDocumentName: "F1002"
      template: "header"
    packageData:
      dtd: "package-data-v1-7.dtd"
      name: "package-data.xml"
      path: "procedures/common/annexf/dtd/WIPO-1.16/package-data-v1-7.dtd"
      version: "1.0"
      xslt: "procedures/common/annexf/xslt/package-data-xml-v1-7.xslt"
      annexFDocumentName: "PACKDATAXML"
    request:
      dtd: "ep-request-v1-15.dtd"
      name: "ep-request.xml"
      path: "NATPAT/annexf/dtd/ep1001/ep-request-v1-15.dtd"
      version: "1.0"
      xslt: "NATPAT/annexf/xslt/request-xml.xslt"
      annexFDocumentName: "REQXML"
    request-pdf:
      name: "ep-request.pdf"
      xslt: "NATPAT/annexf/xslt/request-pdf.xslt"
      annexFDocumentName: "1001P"
      template: "html"
      pdfOverview: true
      customDpi: 2800
      feesParam: true
  filing:
    result-filing:
      dtd: "result-filing.dtd"
      name: "result-filing.xml"
      path: "procedures/common/annexf/dtd/result-filing.dtd"
      version: "1.0"
      xslt: "procedures/common/annexf/xslt/result-filing.xslt"
      annexFDocumentName: "APPMERGEXML"
    submission-transfer:
      dtd: "submission_transfer.dtd"
      name: "submission_transfer.xml"
      path: "procedures/common/annexf/dtd/submission_transfer.dtd"
      version: "2.01"
      xslt: "procedures/common/annexf/xslt/submission-transfer-xml.xslt"
  header:
    header:
      dtd: "pkgheader-v1-4.dtd"
      name: "pkgheader.xml"
      path: "procedures/common/annexf/dtd/WIPO-1.16/pkgheader-v1-4.dtd"
      version: "1.4"
      xslt: "procedures/common/annexf/xslt/package-header-xml-v1-4.xslt"
      annexFDocumentName: "HEADERXML"
  payment:
  receipt:
    receipt:
      dtd: "xmit-receipt-v1-4.dtd"
      name: "xmit-receipt.xml"
      path: "procedures/common/annexf/dtd/WIPO-1.16/xmit-receipt-v1-4.dtd"
      version: "1.4"
      xslt: "procedures/common/annexf/xslt/xmit-receipt-xml-v1-4.xslt"
      annexFDocumentName: "RECXML"
    receipt-pdf:
      name: "receipt.pdf"
      xslt: "NATPAT/annexf/xslt/receipt-pdf.xslt"
      annexFDocumentName: "RECPDF"
      template: "html"
      customDpi: 2800

header:
  receiving-office: "EP"
  country: "EP"
  language: "en"
  ip-type: "patent"
  form-type: "EP1001E2K"
  software-name: "ITC Front Office"
  software-version: ""

xslt:
  params:
    appt-type: "National patent"
    designation: "as-indicated"
    divisional-generation: "2"
    fee-amounts-unlocked-by-user: "no"
    fee-reduction-factor: "1"
    fee-schedule: "0"
    fee-type: "standard"
    lang-code: "epo"
    name-type: "natural"
    petition: "Grant of European patent, and examination of the application under Article 94, are hereby requested."
    place-signed: "place"
    produced-by: "applicant"
    to-pay: "yes"
    waiver-communication: "no"

receipt:
  status: "new"
  name-type: "legal"
  name: "To be defined - This will have to change soon"

wad:
  submission-transfer:
    epo-line-id: "0"
    original-submission-id: "0"
    receiving-office-initial: "FO"
    state-code: "0"
    state-ts: "00000000"
    additional-data-count: "5"
  result-filing:
    status: "new"
    applnr-origin: "generated"
    filing-mode: "online"
    request-entity-name: "ep-request"
    initial-ro: "FO"
    timezone: "CET"
    designation: "as-indicated"
    waiver: ""
    renunciation: ""
    inv-rights-date: ""
    authorisation-code: "1"
    olf-status-id: "0"
    olf-status: "Ok"

numbering:
  prefix: "EP"
  template: "%s%s%05d"
  generator: "epNumberGenerator"
  sequence: "national_sequence"

internal-filing:
  enabled: true
  send-to-backend: false
